[package]
name = "crypto_module"
version = "0.1.0"
authors = ["Colby Cypher Society"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.17"
num = "0.2"
num-traits = "0.2"
rand = "0.5.5"
num-bigint = { version = "0.2.0", features = ["rand"] }
